### ISSUE TITLE
Define API for 32 bit valued functions

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Zero-Allocation-Hashing#1]

**Comment by peter-lawrey** [comment]
Roman, can you provide more details?

**Comment by leventov** [comment]
`LongHashFunction` returns `long`s as hash results. the idea is to provide something like `IntHashFunction` which return `int`s.

**Comment by peter-lawrey** [comment]
Could you not do 

```java
long h64 = hash64(...);
int h32 = (int) ((h64 >>> 32) | h64);
```

**Comment by leventov** [comment]
@peter-lawrey yes, currently people do this. But this looks like the library's job. In the simplest case `IntLongFunction` could do exactly this.

**Comment by pjakubik** [comment]
Should that be
```
long h64 = hash64(...);
int h32 = (int) ((h64 >>> 32) ^ h64);
```
I think you want bitwise exclusive OR, not bitwise OR

**Comment by tgd** [comment]
Closing this out as no work is planned on this at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support and reference this github issue: https://chronicle.software/contact-us/
