### ISSUE TITLE
Add OSGi instructions to bundle

### ISSUE THREAD

**Issue by smigfu** [OpenHFT/Zero-Allocation-Hashing#11]
Enabled the deployment into an OSGi runtime

**Comment by leventov** [comment]
Thank you. Is a new maven release needed?

**Comment by smigfu** [comment]
If this can be done easily it would be great. Thanks!

**Comment by leventov** [comment]
@smigfu released 0.6

**Comment by leventov** [comment]
@smigfu do you have an idea how to combat this Travis failure: https://travis-ci.org/OpenHFT/Zero-Allocation-Hashing/jobs/497552141?
