### ISSUE TITLE
Update compiler settings to Java 8

### ISSUE THREAD

**Issue by smigfu** [OpenHFT/Zero-Allocation-Hashing#13]
Are there any objections to upgrade the project to Java 8? Currently the compiler is set to Java 6.

**Comment by leventov** [comment]
What is the benefit of the upgrade, if the project doesn't use (and need) any Java 7 or Java 8 features? Currently users of older Java versions are supported.

**Comment by smigfu** [comment]
There is no direct benefit, its just the case that Java 7 is end of life. But I guess it is ok to still support those client.

Thanks.
