### ISSUE TITLE
Implementation in an existing non-Maven/Gradle project?

### ISSUE THREAD

**Issue by paulhargreaves** [OpenHFT/Zero-Allocation-Hashing#14]
Sorry for the n00b question, but I'm trying to figure out how to use this a project that is neither using Gradle or Maven.

Is there a suitable guide somewhere? I'm using IntelliJ.

**Comment by leventov** [comment]
You mean that you don't use Maven/Gradle?

1) Download the jar, https://oss.sonatype.org/content/repositories/releases/net/openhft/zero-allocation-hashing/0.6/zero-allocation-hashing-0.6.jar
2) Follow instruction here: http://stackoverflow.com/a/15960913/648955

**Comment by paulhargreaves** [comment]
Thank you, that's perfect.
