### ISSUE TITLE
Question: the least collision rate for UUID like input

### ISSUE THREAD

**Issue by l15k4** [OpenHFT/Zero-Allocation-Hashing#17]
Hey,

I'm trying to avoid using off-heap Map/Set implementations for performance reasons (serialization/deserialization) and a good way of doing that is using `Long` instead of String for UUID like keys and using some Map implementation that doesn't autobox primitives...

I'm just wondering what is the most suitable 64bit hash function? I'm mostly going for the lowest collision rate rather than for performance. I'd just like to have a HashMap/HashSet with up to 30-40M records with the least memory footprint possible without GC overhead and test it for presence of 400M distinct UUIDs. I have no idea what collision rate could be there if I use say murmur3 for 64bit hashing of those UUIDs.

I'm very grateful for your library, it is the only source of 64bit hash functions. I'm kind of terrified of using Guava's 128bit hash functions and then calling : 
http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/hash/HashCode.html#padToLong--

**Comment by peter-lawrey** [comment]
Hello,
Are you trying to minimise allocations on look up? If so you can use a
mutable key provided you don't change it once it has been added to the
collection (you need to ensure keys/elements don't change). If you use a
mutable pair of long you can store a UUID and avoid allocation on a get by
reusing the mutable lookup object to perform the lookup.

e.g.

   LongPair lp = longPairThreadLocal.get();
   lp.set(high, low);
   Value value = map.get(lp);

Regards,
   Peter.

**Comment by l15k4** [comment]
I don't follow this idea to be honest :-)

My use case is having a lookup table with 40M entries like `Map<String, T>` and looking up billions of coming keys.

My concern is mainly memory footprint and GC overhead from having 40M `String` keys. If I hash them as `Long` I'd just have 40M objects less on heap and ~ 40+ bytes less per map entry. It just keeps CPUs busy and eats up almost 2GB of heap... I thought that switching from String to Long using this library could be the right solution.

**Comment by peter-lawrey** [comment]
It would if you go off heap. It will make some difference even if you stay
on heap if you halve the number of objects. Ie using 1 instead of 2 per key
as String does. Using UUID or a mutable version will do that.

If you have 40m entries and only 2 GB you have to limit yourself to 50
bytes per entry. Note. A Long uses 24 bytes. A Map.Entry uses 24 bytes so
you won't have any space for the value which if fine if there are very few
if them.

Note: 1 GB costs less than a hour of your time so it might not be worth
spending too much time to save a GB.

**Comment by l15k4** [comment]
Ok, thank you for the insights !
