### ISSUE TITLE
NoSuchMethodError on Android: Unsafe.getByte

### ISSUE THREAD

**Issue by Alexander--** [OpenHFT/Zero-Allocation-Hashing#18]
Using the library on some Android versions results in following Error:
 
    java.lang.NoSuchMethodError: No virtual method getByte(Ljava/lang/Object;J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
                      at net.openhft.hashing.LongHashFunction.<clinit>(LongHashFunction.java:73)

It does work on Android 7. It seems, older Android versions do not implement full functionality of Unsafe. 

Considering that Unsafe is likely to be replaced/killed off in future versions of mainline Java, you should probably move all related static constants into the UnsafeAccess and add some handling for situations when it is not available.

**Comment by peter-lawrey** [comment]
Correct. We have a Memory class which abstracts this. We look forward to
the public APIs to replace these.

**Comment by leventov** [comment]
@peter-lawrey zero-allocation hashing doesn't use Chronicle-Core/Bytes.

@Alexander-- do you wish to submit a patch to fix this problem on Android versions of your interest? I would not be able to do this because I'm not an Android developer, don't have setup configured, and devices to test the patch on

**Comment by Alexander--** [comment]
@leventov Sorry for delay, I have missed the notification of your reply. Here is a PR as requested — https://github.com/OpenHFT/Zero-Allocation-Hashing/pull/19

**Comment by leventov** [comment]
@Alexander-- thanks, the fix is a part of [the 0.8 release](https://github.com/OpenHFT/Zero-Allocation-Hashing/releases/tag/zero-allocation-hashing-0.8).

**Comment by Nekromancer** [comment]
I've got similar issue in 0.9 version. Stack trace:
![image](https://user-images.githubusercontent.com/3933348/68371370-e0d6e000-013e-11ea-857f-6986e9ad038b.png)

**Comment by Alexander--** [comment]
> I've got similar issue in 0.9 version

@Nekromancer

This is the same issue. Unsafe didn't magically start working on pre-Nougat Android!

If you look at my patch, you will see that I simply wrapped some static initialization within `LongHashFunction` in try-catch. This avoids crash during class-loading and allows you to substitute `UnsafeAccess` with your own `Access` subclass.
