### ISSUE TITLE
Add t1ha

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Zero-Allocation-Hashing#23]
https://github.com/leo-yuriev/t1ha

**Comment by leo-yuriev** [comment]
This is a problem, since java does not have 64-bit unsigned integers. Therefore wide multiplication (64x64 -> 128) will be unacceptably slow in java implementation.

**Comment by leventov** [comment]
There is [`Math.multiplyHigh(long, long)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Math.html#multiplyHigh(long,long)) which is supposed to map onto a single x86 instruction since Java 10: https://bugs.openjdk.java.net/browse/JDK-8187684

**Comment by leo-yuriev** [comment]
It is not enough, anyway something like [`_mymum()`](https://github.com/OpenHFT/Zero-Allocation-Hashing/blob/master/src/main/java/net/openhft/hashing/WyHash.java#L26-L39) is needed.

The proper way is provide [`_umul128()`](https://docs.microsoft.com/en-us/cpp/intrinsics/umul128) for Java.

**Comment by tgd** [comment]
Closing this out as no work is planned on this at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support and reference this github issue: https://chronicle.software/contact-us/
