### ISSUE TITLE
use jdk native  Math.multiplyHigh() to improve performance

### ISSUE THREAD

**Issue by gzm55** [OpenHFT/Zero-Allocation-Hashing#42]
From JDK10, `Math.multiplyHigh()` is optimized as hardware instructions on x86 and arm. This can improve the performance of `64x64_fold` mix steps, which is used in many good hash, such as xx3, tiha, wyhash, mum and etc. On my local test, the `wy_3()` is improved significantly.

`Math.multiplyHigh()` was introduced from JDK9, so we need some tricks for compiling on JDK7&8, and avoid method reflection invocations.

**Comment by gzm55** [comment]
@RobAustin which version of JDK do we use to build the release artifacts?

**Comment by dpisklov** [comment]
Java 8, oracle's jdk
