### ISSUE TITLE
Release 0.12 with 128 bit hashes

### ISSUE THREAD

**Issue by paplorinc** [OpenHFT/Zero-Allocation-Hashing#50]
`0.11` doesn't seem to contain murmur 128 yet - any plans to release it?

**Comment by gzm55** [comment]
@dpisklov @leventov ?

**Comment by RobAustin** [comment]
if you are able to submit a pull request ( to include the change ) we can release it.

**Comment by paplorinc** [comment]
It would suffice for me if the latest version were released, since `0.11` doesn't seem to contain [LongTupleHashFunction](https://github.com/OpenHFT/Zero-Allocation-Hashing/blob/a5ce46b4557f38a39f56ee83e50d5bcbc9d95dbc/src/main/java/net/openhft/hashing/LongTupleHashFunction.java#L76) yet, so I can't hash 128 bits, right?

**Comment by dpisklov** [comment]
This has been released
