### ISSUE TITLE
XXH3_128bits

### ISSUE THREAD

**Issue by stychu** [OpenHFT/Zero-Allocation-Hashing#54]
Is the 128-bit version on the road map maybe ??

**Comment by gzm55** [comment]
it could take sometime to develop, welcome to contribute

**Comment by gzm55** [comment]
@leventov according to [xxh3](https://github.com/Cyan4973/xxHash/blob/c50e1b148f5bf62bb345572a2034422dc28c1eb6/xxhash.h#L4477), the seed variant seems have to alloc an secret array.

**Comment by gzm55** [comment]
it seems that the xxh3 (64bits and 128bits) use many internal state, e.g. (`secret`, `acc`, etc.), the performance is about 2x slow than xxhash64.
