### ISSUE TITLE
Release to Maven central

### ISSUE THREAD

**Issue by paplorinc** [OpenHFT/Zero-Allocation-Hashing#59]
The latest available one seems to be 0.12

**Comment by gzm55** [comment]
@dpisklov @RobAustin

**Comment by paplorinc** [comment]
Any progress?

**Comment by gzm55** [comment]
@dpisklov @RobAustin xxh3 and xxh128 are merged, we would better release 0.15 and publish to the central.

**Comment by JCotton1123** [comment]
We’re trying to make use of xxh128 and would prefer to source this from Maven. Plus 1 for publishing the latest version to maven.

**Comment by gzm55** [comment]
jar and javadoc of 0.15 are official released
