### ISSUE TITLE
How to build to a jar? Can't find main class

### ISSUE THREAD

**Issue by YWaller** [OpenHFT/Zero-Allocation-Hashing#61]
Hi, there's a branch of this with 128 bit xxhashing in it that I need, and I'm trying to build it in intellij to a jar but I can't find the main class? How should I go about producing a jar that other projects can reference?

Thank you very much.

**Comment by gzm55** [comment]
the pr is merged. Before publish to the maven central, you can build the jar from the latest master by `mvn package` command

**Comment by YWaller** [comment]
Ah very good, I just assumed it wouldn't be merged forever since it had been open for a month or so. Thank you for your assistance!
