### ISSUE TITLE
Endianness and hashLong

### ISSUE THREAD

**Issue by svladykin** [OpenHFT/Zero-Allocation-Hashing#66]
I see that `hashLong` rotates input on Big Endian platforms with `Primitives.nativeToLittleEndian`:

https://github.com/OpenHFT/Zero-Allocation-Hashing/blob/303f1a5dba00af1f5482b68e5f3884924bdfe620/src/main/java/net/openhft/hashing/XxHash.java#L155

Do I understand correct that `hashLong(1L)` will not return the same result on Big and Little Endian platforms?

**Comment by gzm55** [comment]
The portability is defined by the hash algorithm, here your example [xxhash](https://github.com/Cyan4973/xxHash#xxhash---extremely-fast-hash-algorithm), not by the interface `hashLong()`. You can also find the portability description in the [javadoc](https://javadoc.io/doc/net.openhft/zero-allocation-hashing/latest/net/openhft/hashing/LongHashFunction.html) of zah for every implemented hash algorithms.
