### ISSUE TITLE
Github Action fails on pull request: Build and analyze

### ISSUE THREAD

**Issue by gzm55** [OpenHFT/Zero-Allocation-Hashing#71]
1. warning message: The requested profile "sonar" could not be activated because it does not exist.
2. skip this action on pull requests since the action cannot read SONAR_TOKEN (https://github.com/OpenHFT/Zero-Allocation-Hashing/runs/4850112661?check_suite_focus=true)

@RobAustin

**Comment by minborg** [comment]
We should add the profile.

**Comment by RobAustin** [comment]
@minborg I'm going to close this issue, -please reopen if required.
